version: '3'
services:

networks:
    app-tier:
      driver: bridge

services:

  nginxserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/web
      - "./vhost.conf:/etc/nginx/conf.d/default.conf"
    depends_on: 
      - phpfpm
    networks:
    - app-tier

  phpfpm:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/bitnami/php-fpm:7.4-debian-10'
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./web:/web
    networks:
        - app-tier