version: '3.5'
services: 
    flask:
        build: 
            context: .
            dockerfile: Dockerfile-flask
        volumes:
            - .:/app

    nginx:
        build: 
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - .:/app
        ports:
            - 8084:80


