version: '3'
services:
  nginxserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - "./vhost.conf:/etc/nginx/conf.d/default.conf" 
      - "./web:/var/www/html"
  phpfpm:
    image: php:7.2-fpm
    container_name: php-fpm
    volumes: 
      - "./web:/var/www/html"
    ports:
      - "9000"
    # command: "docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli"
    # command: "docker-php-ext-enable mysqli"
    command:
      - /bin/sh
      - -c
      - |
          docker-php-ext-install mysqli
          docker-php-ext-enable mysqli
          php-fpm
      
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e
    ports:
      - "3306:3306"
