version: '3'
services:
    php-server:
        image: webdevops/php-apache:7.1-alpine
        container_name: php-server
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        networks: 
            - app-net
        volumes: 
            - "./web:/app"

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e
        ports:
            - "3306:3306"
        networks: 
            - app-net

networks:
    app-net:
        driver: bridge